export enum Sources {
	ARES = "ARES",
	GALAXYMANGA = "GALAXYMANGA",
	MANGALEK = "MANGALEK",
	MANGASPARK = "MANGASPARK",
	AZORA = "AZORA",
	MANGASWAT = "MANGASWAT",
	MANGAAE = "MANGAAE",
	OZULSCANS = "OZULSCANS",
}
