export enum Sources {
	ARES = "ARES",
	GALAXYMANGA = "GALAXYMANGA",
	MANGALEK = "MANGALEK",
	MANGASPARK = "MANGASPARK",
	AZORA = "AZORA",
	MANGASWAT = "MANGASWAT",
	OZULSCANS = "OZULSCANS",
	TEAMX = "TEAMX",
	STKISSMANGA = "STKISSMANGA",
	KISSMANGA = "KISSMANGA",
	MANGAPROTM = "MANGAPROTM",
	ARENASCANS = "ARENASCANS",
	ASHQ = "ASHQ",
	MANGAKAKALOT = "MANGAKAKALOT",
	ANILIST = "ANILIST",
	MANGADEX = "MANGADEX",
}


