export enum Sources {
	ARES = "ARES",
	FLAMESCANS = "FLAMESCANS",
	MANGALEK = "MANGALEK",
	MANGASPARK = "MANGASPARK",
	AZORA = "AZORA",
	MANGASWAT = "MANGASWAT",
	MANGAAE = "MANGAAE",
	OZULSCANS = "OZULSCANS",
}
